// templates/vue-ts/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)
</script>

<template>
  <div class="flex flex-col items-center justify-center min-h-screen bg-gray-100 text-gray-800">
    <h1 class="text-4xl font-bold mb-4">Vite + Vue + TS + Tailwind</h1>
    <div class="card p-6 bg-white rounded-lg shadow-md">
      <button 
        class="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition" 
        @click="count++"
      >
        count is {{ count }}
      </button>
      <p class="mt-4 text-gray-600">
        Edit <code>src/App.vue</code> and save to test HMR
      </p>
    </div>
  </div>
</template>

// templates/react-ts/src/App.tsx
import { useState } from 'react'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100 text-gray-800">
      <h1 className="text-4xl font-bold mb-4">Vite + React + TS + Tailwind</h1>
      <div className="card p-6 bg-white rounded-lg shadow-md">
        <button 
          className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition"
          onClick={() => setCount((count) => count + 1)}
        >
          count is {count}
        </button>
        <p className="mt-4 text-gray-600">
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
    </div>
  )
}

export default App
